# ruff: noqa: E402, E501
"""Smoke test for intel-company v2 — 3-track pipeline with full pipeline health tracking.

Tests the full call path:
  Track 1: WebFetch (leadership, IR, newsroom pages via shared browser infra)
  Track 2: Perplexity sonar-pro (web research)
  Track 3: Synthesis LLM (Gemini reconciliation)

Every failure, fallback, and degradation is captured in PipelineHealthLog
and surfaced in both the markdown report and JSON output.

Usage:
    python3 scripts/smoke_test_intel_company.py nike.com
    python3 scripts/smoke_test_intel_company.py orientaltrading.com
"""

from __future__ import annotations

import asyncio
import json
import sys
import uuid
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from prism_platform.config import settings
from prism_platform.v2.research_client import make_research_client
from prism_platform.v2.executor import ModuleExecutor
from prism_platform.db.cache import get_cached_result, persist_result
from prism_platform.v2.modules.intel_company.fetcher import fetch_all_company_pages
from prism_platform.v2.modules.intel_company.schemas import CompanySeedOutput
from prism_platform.v2.pipeline_health import PipelineHealthLog
from prism_platform.v2.registry import V2_MODULE_REGISTRY, register_all_v2_modules
from prism_platform.v2.synthesis import SynthesisClient
from prism_platform.v2.types import ExecutionContextV2

BANNER = "=" * 70

AUDIT_OUTPUT_ROOT = ROOT / "TEMP" / "audits"
SYNTHESIS_PLAYBOOK = ROOT / "prism_platform" / "v2" / "modules" / "intel_company" / "playbook_synthesis.md"


def _fmt_usd(val: float | None) -> str:
    if val is None:
        return "unknown"
    if val >= 1e9:
        return f"${val / 1e9:.1f}B"
    if val >= 1e6:
        return f"${val / 1e6:.0f}M"
    return f"${val:,.0f}"


def _write_markdown(
    domain: str,
    output: CompanySeedOutput,
    citations: list[str],
    synthesis_model: str,
    health: PipelineHealthLog,
) -> Path:
    """Write CompanySeedOutput + pipeline health to markdown."""
    out_dir = AUDIT_OUTPUT_ROOT / domain
    out_dir.mkdir(parents=True, exist_ok=True)
    md_path = out_dir / "01-company-context.md"

    execs_md = "\n".join(
        f"| {e.full_name} | {e.title} | {e.role_classification or '—'} | "
        f"{e.linkedin_url or '—'} |"
        for e in output.executives
    )

    comps_md = "\n".join(
        f"| {c.company_name} | {c.domain} | {c.ticker or '—'} | "
        f"{c.twitter_handle or '—'} | {c.linkedin_url or '—'} |"
        for c in output.competitors
    )

    citations_md = "\n".join(f"- {url}" for url in citations[:10])
    health_md = health.to_markdown()

    content = f"""# Company Intelligence — {output.common_name}
> Generated by intel-company v2.2.0 (3-track pipeline) | {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}
> Track 1: WebFetch (shared browser infra) | Track 2: Perplexity sonar-pro | Track 3: {synthesis_model}
> Domain: {domain} | Pipeline status: **{health.overall_status}**

---

{health_md}

---

## Identity

| Field | Value |
|---|---|
| Legal Name | {output.legal_name} |
| Common Name | {output.common_name} |
| Domain | {output.domain} |
| Headquarters | {output.headquarters} |
| Founded | {output.year_founded or '—'} |
| Employees | {f"{output.employee_count:,}" if output.employee_count else '—'} ({output.employee_count_source or '—'}) |
| Industry | {output.industry} |
| Sub-vertical | {output.sub_vertical or '—'} |
| Public | {'Yes — ' + output.ticker if output.is_public and output.ticker else 'Yes' if output.is_public else 'No (Private)'} |
| Revenue Estimate | {_fmt_usd(output.revenue_estimate)} ({output.revenue_source or '—'}) |
| Parent Company | {output.parent_company or '—'} |

## Business Model

{output.business_model}

## Social Presence

| Channel | Handle / URL |
|---|---|
| LinkedIn | {output.company_linkedin_url or '—'} |
| Twitter/X | {'@' + output.twitter_handle if output.twitter_handle else '—'} |
| YouTube | {output.youtube_url or '—'} |

## Product Categories

{chr(10).join('- ' + cat for cat in output.product_categories)}

## Leadership Team

| Name | Title | MEDDPICC Role | LinkedIn |
|---|---|---|---|
{execs_md}

## Competitors

| Company | Domain | Ticker | Twitter | LinkedIn |
|---|---|---|---|---|
{comps_md}

## Recent Headline

{output.recent_headline or 'No recent headline found (last 90 days).'}

## Sources

{citations_md}
"""
    md_path.write_text(content, encoding="utf-8")
    return md_path


def _write_json(
    domain: str,
    output: CompanySeedOutput,
    result_meta: dict,
    health: PipelineHealthLog,
) -> Path:
    """Write CompanySeedOutput + pipeline health to JSON."""
    out_dir = AUDIT_OUTPUT_ROOT / domain
    out_dir.mkdir(parents=True, exist_ok=True)
    json_path = out_dir / "01-company-context.json"

    payload = {
        "module": "intel-company",
        "version": "2.2.0",
        "pipeline": "3-track",
        "domain": domain,
        "generated_at": datetime.now(UTC).isoformat(),
        "pipeline_health": health.summary(),
        "track1_pages_found": result_meta.get("track1_pages_found", 0),
        "track2_duration_ms": result_meta.get("track2_duration_ms"),
        "track3_duration_ms": result_meta.get("track3_duration_ms"),
        "track3_model": result_meta.get("track3_model", ""),
        "citations": result_meta.get("citations", []),
        "output": output.model_dump(),
    }
    json_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return json_path


async def _try_persist_to_db(result, context: ExecutionContextV2, handle, health: PipelineHealthLog) -> str:
    """Attempt to write to accounts table. Returns status string."""
    try:
        from sqlalchemy import select

        from prism_platform.db.models import Account
        from prism_platform.db.session import async_session_factory

        async with async_session_factory() as session:
            existing = await session.execute(
                select(Account).where(Account.domain == context.account_domain).limit(1)
            )
            if existing.scalar_one_or_none() is None:
                account = Account(
                    domain=context.account_domain,
                    company_name=context.company_name,
                )
                session.add(account)
                await session.commit()

        if handle.post_execute:
            await handle.post_execute(result, context)
        health.info("db_persist", "Data persisted to accounts table")
        return "written"
    except Exception as exc:
        msg = f"{exc.__class__.__name__}: {exc}"
        health.warning("db_persist", f"DB persist skipped — {msg}", error=msg)
        return f"skipped ({msg})"


async def run(domain: str, force_refresh: bool = False) -> None:
    api_key = settings.perplexity_api_key
    if not api_key:
        print("ERROR: PERPLEXITY_API_KEY not set in .env")
        sys.exit(1)

    register_all_v2_modules()
    handle = V2_MODULE_REGISTRY["intel-company"]

    # Initialize pipeline health log
    health = PipelineHealthLog(module_name="intel-company", domain=domain)

    print(BANNER)
    print("PRISM v2.2 — intel-company 3-track pipeline")
    print(f"Target domain : {domain}")
    print(f"Module        : {handle.name} v{handle.version}")
    print("Pipeline      : Track 1 (WebFetch) → Track 2 (Perplexity) → Track 3 (Synthesis)")
    print(BANNER)

    audit_id = str(uuid.uuid4())
    context = ExecutionContextV2(
        audit_id=audit_id,
        account_domain=domain,
        company_name=domain.split(".")[0].title(),
    )

    # =========================================================================
    # CACHE CHECK — skip all 3 tracks if fresh data already exists
    # =========================================================================
    print(f"\nChecking cache for {domain}...")
    cached = await get_cached_result("intel-company", domain)
    if cached and not force_refresh:
        print(f"CACHE HIT — data already exists (age: {cached.get('executed_at', 'unknown')})")
        print("Skipping all 3 tracks — zero API calls made.")
        print("To force a refresh: python3 scripts/smoke_test_intel_company.py {domain} --refresh")
        output = CompanySeedOutput.model_validate(cached["output"])
        citations = cached.get("sources", [])
        # Write outputs from cached data
        health.info("cache", f"Cache hit — served from module_executions", executed_at=cached.get("executed_at"))
        md_path = _write_markdown(domain, output, citations, "cached", health)
        json_path = _write_json(domain, output, {"citations": citations, "track1_pages_found": 0, "track2_duration_ms": 0, "track3_duration_ms": 0, "track3_model": "cached"}, health)
        print(f"Markdown out  : {md_path.relative_to(ROOT)}")
        print(f"JSON out      : {json_path.relative_to(ROOT)}")
        print(f"\nExecutives ({len(output.executives)}): {', '.join(e.full_name for e in output.executives[:3])}{'...' if len(output.executives) > 3 else ''}")
        print(f"Competitors  ({len(output.competitors)}): {', '.join(c.company_name for c in output.competitors[:3])}...")
        return
    elif cached and force_refresh:
        print(f"Cache exists but --refresh requested — running full pipeline")
    else:
        print(f"Cache miss — running full 3-track pipeline")

    # =========================================================================
    # TRACK 1: WebFetch
    # =========================================================================
    print(f"\n{'─' * 50}")
    print(f"TRACK 1: WebFetch — fetching company pages for {domain}")
    print(f"{'─' * 50}")

    pages = await fetch_all_company_pages(domain, timeout=20.0)

    track1_pages_found = 0
    for page_type, content in pages.items():
        if content:
            track1_pages_found += 1
            health.info("track1_webfetch", f"{page_type} fetched ({len(content):,} chars)", page_type=page_type, chars=len(content))
            print(f"  [{page_type}] {len(content):,} chars fetched")
        else:
            health.warning("track1_webfetch", f"{page_type} not found — page does not exist or was blocked", page_type=page_type)
            print(f"  [{page_type}] not found")

    if track1_pages_found == 0:
        health.error("track1_webfetch", "No company pages fetched — Track 2 (Perplexity) is the sole data source. Output may have reduced accuracy for executive data and company details.", pages_tried=["leadership", "ir", "newsroom"])

    # Inject fetched pages into context
    for key, content in pages.items():
        if content:
            context.upstream_results[key] = content

    # =========================================================================
    # TRACK 2: Perplexity
    # =========================================================================
    print(f"\n{'─' * 50}")
    print(f"TRACK 2: Perplexity sonar-pro — web research for {domain}")
    print(f"{'─' * 50}")
    print("(This takes 10-30 seconds)\n")

    api = make_research_client(timeout=120.0)
    executor = ModuleExecutor(agent_api=api)

    track2_result = await executor.execute(
        config=handle.config,
        context=context,
        output_schema=handle.output_schema,
        playbook_path=handle.playbook_path,
    )

    print(f"  Status        : {track2_result.status.upper()}")
    print(f"  LLM calls     : {track2_result.llm_calls}")
    print(f"  Duration      : {track2_result.duration_ms}ms")
    print(f"  Citations     : {len(track2_result.citations)}")

    if track2_result.status == "success":
        health.info("track2_perplexity", f"Perplexity call succeeded ({track2_result.duration_ms}ms, {len(track2_result.citations)} citations)", duration_ms=track2_result.duration_ms, citations=len(track2_result.citations))
    else:
        health.critical("track2_perplexity", f"Perplexity call FAILED — {', '.join(track2_result.errors)}", errors=track2_result.errors)
        print("\n  TRACK 2 FAILED:")
        for err in track2_result.errors:
            print(f"    - {err}")
        sys.exit(1)

    track2_output = track2_result.output or {}

    # =========================================================================
    # TRACK 3: Synthesis
    # =========================================================================
    print(f"\n{'─' * 50}")
    print(f"TRACK 3: Synthesis — reconciling Track 1 + Track 2")
    print(f"{'─' * 50}")

    synthesis_client = SynthesisClient()

    template_vars = {
        "domain": domain,
        "company_name": domain.split(".")[0].title(),
        "upstream_leadership_page": pages.get("leadership_page", ""),
        "upstream_ir_page": pages.get("ir_page", ""),
        "upstream_newsroom_page": pages.get("newsroom_page", ""),
        "upstream_perplexity_output": json.dumps(track2_output, indent=2),
        "upstream_perplexity_citations": ", ".join(track2_result.citations[:10]),
    }

    synthesis_result = await synthesis_client.synthesize(
        playbook_path=SYNTHESIS_PLAYBOOK,
        template_vars=template_vars,
        output_schema=CompanySeedOutput,
    )

    print(f"  Status        : {synthesis_result.status.upper()}")
    print(f"  Model         : {synthesis_result.model_used}")
    print(f"  Duration      : {synthesis_result.duration_ms}ms")

    if synthesis_result.status != "success":
        health.error("track3_synthesis", f"Synthesis failed — {synthesis_result.error}. Falling back to Track 2 output only.", error=synthesis_result.error, model=synthesis_result.model_used)
        print(f"  ERROR         : {synthesis_result.error}")
        print("\n  Falling back to Track 2 output only")
        output = CompanySeedOutput.model_validate(track2_output)
        synthesis_model = "fallback (Track 2 only)"
    else:
        try:
            output = CompanySeedOutput.model_validate(synthesis_result.output)
            synthesis_model = synthesis_result.model_used
            health.info("track3_synthesis", f"Synthesis succeeded ({synthesis_result.duration_ms}ms, model: {synthesis_model})", duration_ms=synthesis_result.duration_ms, model=synthesis_model)
            print("  Schema valid  : YES")
        except Exception as exc:
            health.error("track3_synthesis", f"Synthesis output failed schema validation — {exc}. Falling back to Track 2 output.", error=str(exc), model=synthesis_result.model_used)
            print(f"  Schema valid  : NO — {exc}")
            print("  Falling back to Track 2 output")
            output = CompanySeedOutput.model_validate(track2_output)
            synthesis_model = "fallback (Track 2 only)"

    # =========================================================================
    # DATA QUALITY VALIDATION
    # =========================================================================
    exec_count = len(output.executives)
    comp_count = len(output.competitors)

    if exec_count < 5:
        health.warning("validation", f"Only {exec_count} executives found (minimum target: 5). Executive coverage is incomplete — outreach may miss key decision-makers.", found=exec_count, target=5)
    if exec_count == 0:
        health.critical("validation", "ZERO executives found. Leadership data is completely missing. Manual research required before any outreach.")
    if comp_count < 5:
        health.warning("validation", f"Only {comp_count} competitors found (minimum target: 5). Competitive landscape is incomplete.", found=comp_count, target=5)

    # Check for missing social URLs
    missing_social = []
    if not output.company_linkedin_url:
        missing_social.append("LinkedIn")
    if not output.twitter_handle:
        missing_social.append("Twitter")
    if not output.youtube_url:
        missing_social.append("YouTube")
    if missing_social:
        health.warning("validation", f"Company social URLs missing: {', '.join(missing_social)}. These may need manual lookup.", missing=missing_social)

    # Check exec LinkedIn coverage
    execs_with_linkedin = sum(1 for e in output.executives if e.linkedin_url)
    if exec_count > 0 and execs_with_linkedin == 0:
        health.warning("validation", "No executive LinkedIn profile URLs found. Outreach will require manual LinkedIn search.", execs_total=exec_count, execs_with_linkedin=0)
    elif exec_count > 0 and execs_with_linkedin < exec_count:
        health.info("validation", f"LinkedIn URLs found for {execs_with_linkedin}/{exec_count} executives.", execs_with_linkedin=execs_with_linkedin, execs_total=exec_count)

    if not output.revenue_estimate:
        health.warning("validation", "Revenue estimate not available. Financial sizing for the opportunity will need manual research.", field="revenue_estimate")

    # --- Persist to DB (accounts table via post_execute hook) ---
    db_status = await _try_persist_to_db(track2_result, context, handle, health)
    print(f"\nDB persist    : {db_status}")

    # --- Persist final synthesized result to module_executions cache ---
    # This ensures subsequent runs hit the cache and skip all 3 API tracks.
    final_result_dict = {
        "module_name": "intel-company",
        "module_version": "2.2.0",
        "status": "success",
        "output": output.model_dump(),
        "sources": track2_result.citations,
        "duration_ms": track2_result.duration_ms + synthesis_result.duration_ms,
        "llm_calls": track2_result.llm_calls + 1,
        "llm_cost_usd": 0.0,
        "errors": [],
        "warnings": [],
        "pipeline_health": health.summary(),
    }
    try:
        await persist_result(
            module_name="intel-company",
            domain=domain,
            result_dict=final_result_dict,
            audit_id=None,  # Smoke test runs outside Temporal — no audits table row
        )
        health.info("cache", f"Synthesized result persisted to module_executions — future runs will use cache")
        print(f"Cache persist : written to module_executions")
    except Exception as exc:
        health.warning("cache", f"module_executions persist failed — {exc}", error=str(exc))
        print(f"Cache persist : skipped ({exc.__class__.__name__}: {exc})")

    # --- Write outputs ---
    md_path = _write_markdown(domain, output, track2_result.citations, synthesis_model, health)
    json_path = _write_json(domain, output, {
        "track1_pages_found": track1_pages_found,
        "track2_duration_ms": track2_result.duration_ms,
        "track3_duration_ms": synthesis_result.duration_ms,
        "track3_model": synthesis_model,
        "citations": track2_result.citations,
    }, health)
    print(f"Markdown out  : {md_path.relative_to(ROOT)}")
    print(f"JSON out      : {json_path.relative_to(ROOT)}")

    # =========================================================================
    # IDENTITY CARD
    # =========================================================================
    print(f"\n{BANNER}")
    print("COMPANY IDENTITY CARD (SYNTHESIZED)")
    print(BANNER)
    print(f"  Legal name    : {output.legal_name}")
    print(f"  Common name   : {output.common_name}")
    print(f"  Domain        : {output.domain}")
    print(f"  HQ            : {output.headquarters}")
    print(f"  Founded       : {output.year_founded}")
    if output.employee_count:
        print(f"  Employees     : {output.employee_count:,} ({output.employee_count_source or '—'})")
    print(f"  Industry      : {output.industry}")
    print(f"  Sub-vertical  : {output.sub_vertical or 'n/a'}")
    print(f"  Public        : {output.is_public}{' (' + output.ticker + ')' if output.ticker else ''}")
    print(f"  Revenue       : {_fmt_usd(output.revenue_estimate)} ({output.revenue_source or '—'})")
    if output.parent_company:
        print(f"  Parent        : {output.parent_company}")

    print("\n  Business model:")
    print(f"    {output.business_model[:220]}{'...' if len(output.business_model) > 220 else ''}")

    print("\n  Company social:")
    print(f"    LinkedIn : {output.company_linkedin_url or 'not found'}")
    print(f"    Twitter  : @{output.twitter_handle}" if output.twitter_handle else "    Twitter  : not found")
    print(f"    YouTube  : {output.youtube_url or 'not found'}")

    print(f"\n  Executives ({len(output.executives)}):")
    for exec_ in output.executives:
        badge = f" [{exec_.role_classification}]" if exec_.role_classification else ""
        li = f" — {exec_.linkedin_url}" if exec_.linkedin_url else ""
        print(f"    • {exec_.full_name} — {exec_.title}{badge}{li}")

    print(f"\n  Competitors ({len(output.competitors)}):")
    for comp in output.competitors:
        ticker_str = f" | {comp.ticker}" if comp.ticker else ""
        tw_str = f" | @{comp.twitter_handle}" if comp.twitter_handle else ""
        li_str = f" | {comp.linkedin_url}" if comp.linkedin_url else ""
        print(f"    • {comp.company_name} ({comp.domain}){ticker_str}{tw_str}{li_str}")

    print(f"\n  Product categories: {', '.join(output.product_categories)}")
    print(f"\n  Recent headline: {output.recent_headline or 'n/a'}")

    print("\n  Citations (top 5):")
    for i, url in enumerate(track2_result.citations[:5], 1):
        print(f"    {i}. {url}")

    # =========================================================================
    # PIPELINE HEALTH REPORT
    # =========================================================================
    print(f"\n{BANNER}")
    print("PIPELINE HEALTH REPORT")
    print(BANNER)
    print(f"  Overall status: {health.overall_status}")

    for event in health.events:
        if event.severity.value == "info":
            continue  # Skip info in console — only show warnings/errors
        icon = {"warning": "WARN", "error": "ERR ", "critical": "CRIT"}[event.severity.value]
        print(f"  [{icon}] [{event.category.value}] {event.message}")

    # =========================================================================
    # VALIDATION GATES
    # =========================================================================
    print(f"\n{BANNER}")
    print("VALIDATION GATES")
    print(BANNER)

    gates = [
        ("Schema validates", True),
        (f"Executives {exec_count} >= 5", exec_count >= 5),
        (f"Competitors {comp_count} >= 5", comp_count >= 5),
        ("Business model >= 50 chars", len(output.business_model) >= 50),
        ("Revenue is float or None", isinstance(output.revenue_estimate, (float, type(None)))),
        ("Has citations", len(track2_result.citations) > 0),
        ("Markdown written", md_path.exists()),
        ("JSON written", json_path.exists()),
        (f"Track 1 found {track1_pages_found} pages", track1_pages_found >= 1),
        (f"Track 3 synthesis: {synthesis_result.status}", synthesis_result.status == "success"),
        (f"Pipeline health: {health.overall_status}", health.overall_status != "FAILED"),
    ]

    all_pass = True
    for label, passed in gates:
        print(f"  [{'PASS' if passed else 'FAIL'}] {label}")
        if not passed:
            all_pass = False

    print(BANNER)
    if all_pass:
        print(f"ALL GATES PASSED — intel-company 3-track pipeline working for {domain}")
    else:
        print("SOME GATES FAILED — see Pipeline Health Report above for details")
        sys.exit(1)


if __name__ == "__main__":
    domain = sys.argv[1] if len(sys.argv) > 1 else "nike.com"
    force_refresh = "--refresh" in sys.argv
    asyncio.run(run(domain, force_refresh=force_refresh))
